-- 코드를 입력하세요
SELECT MEMBER_ID, MEMBER_NAME, GENDER, LEFT(DATE_OF_BIRTH, 10) AS DATE_OF_BIRTH
from MEMBER_PROFILE
where GENDER = 'W'AND SUBSTRING(DATE_OF_BIRTH, 6,7) = 03 and TLNO != 'null'
order by MEMBER_ID ASC;